#pragma once
#include <iostream>
#include <math.h>
#include <windows.h>
#include <cstdint>
#include <vector>
#include "Entity.h"
#include "EntityList.h"
#include "MemoryManager.h"
#include "Aimbot.h"
#include "Offset.h"